# This is an example of a deployment - a declaration of pods.
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "ttt-deployment"
  namespace: "training"
  labels:
    app: "ttt"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ttt"
  template:
    metadata:
      labels:
        app: "ttt"
    spec:
      containers:
        - image: "850603229734.dkr.ecr.ap-southeast-2.amazonaws.com/fma-tic-tac-toe:latest"
          name: ttt
          resources:
            limits:
              memory: "700Mi"
            requests:
              memory: "100Mi" 
          ports:
            - containerPort: 3000
 
 
# This is an example of a service - a logical grouping of pods
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: "ttt-service"
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: "ttt"
 
# This is an example of an ingress - a way to forward traffic to
# your services and provide SSL termination.
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    "kubernetes.io/tls-acme": "true"
  name: "ttt-ingress"
spec:
  rules:
    - host: "ttt.svc.platform.myobdev.com"
      http:
        paths:
          - backend:
              serviceName: "ttt-service"
              servicePort: 80
            path: /
  tls:
    - hosts:
        - "ttt.svc.platform.myobdev.com"
      secretName: "ttt-tls"